name: Build docker-cli-updater binaries

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.25
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      
      - name: Install dependencies
        run: bun install --production
      
      - name: Save dependencies cache
        uses: actions/cache/save@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Remove cpu-features packages
        run: rm -rf node_modules/cpu-features

      - name: Build binary for running in bun and compiled
        run: |
          bun run build:bun
          bun run build:compile

      - name: Zip binaries for bun
        run: |
          tar -czvf docker-cli-updater_bun.tar.gz bin/bun

      - name: Save artifacts for bun
        uses: actions/upload-artifact@v4
        with:
          name: docker-cli-updater_bun.tar.gz
          path: docker-cli-updater_bun.tar.gz
      
      - name: Save artifacts for others
        uses: actions/upload-artifact@v4
        with:
          name: docker-cli-updater
          path: src/docker-cli-updater
  
      - name: Publish binaries in a Github release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            docker-cli-updater_bun.tar.gz
            src/docker-cli-updater
          body: |
            This is an automated release of docker-cli-updater ${{ github.ref_name }}.
          draft: false
          prerelease: false
          generate_release_notes: false
